# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constrains.xdc

# Block Designs: bd/BlockDesign/BlockDesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign || ORIG_REF_NAME==BlockDesign} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_Clock_divider_0_0/BlockDesign_Clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_Clock_divider_0_0 || ORIG_REF_NAME==BlockDesign_Clock_divider_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_Clock_divider_1_0/BlockDesign_Clock_divider_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_Clock_divider_1_0 || ORIG_REF_NAME==BlockDesign_Clock_divider_1_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_Clock_divider_2_0/BlockDesign_Clock_divider_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_Clock_divider_2_0 || ORIG_REF_NAME==BlockDesign_Clock_divider_2_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_Clock_divider_3_0/BlockDesign_Clock_divider_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_Clock_divider_3_0 || ORIG_REF_NAME==BlockDesign_Clock_divider_3_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_AndModule_0_0/BlockDesign_AndModule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_AndModule_0_0 || ORIG_REF_NAME==BlockDesign_AndModule_0_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_AndModule_1_0/BlockDesign_AndModule_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_AndModule_1_0 || ORIG_REF_NAME==BlockDesign_AndModule_1_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_AndModule_2_0/BlockDesign_AndModule_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_AndModule_2_0 || ORIG_REF_NAME==BlockDesign_AndModule_2_0} -quiet] -quiet

# IP: bd/BlockDesign/ip/BlockDesign_AndModule_3_0/BlockDesign_AndModule_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BlockDesign_AndModule_3_0 || ORIG_REF_NAME==BlockDesign_AndModule_3_0} -quiet] -quiet

# XDC: /home/rootuser/Desktop/Vivado/Clock_divider_with_SW/Clock_divider.gen/sources_1/bd/BlockDesign/BlockDesign_ooc.xdc
